release:
  branches:
    - main
  plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - "@semantic-release/github"
    - "@semantic-release/git"
    - "@semantic-release/exec"
    - "@rimac-technology/semantic-release-s3"
  analyzeCommits:
    - path: "@semantic-release/commit-analyzer"
      releaseRules:
        - type: "feat"
          release: "patch"
        - type: "hotfix"
          release: "patch"
        - type: "patch"
          release: "patch"
        - type: "minor"
          release: "minor"
        - type: "breaking"
          release: "major"
  generateNotes:
    - path: "@semantic-release/release-notes-generator"
      types:
        - type: "feat"
        - section: "Features"
        # Tracked bug fix with a hotfix branch
        - type: "hotfix"
        - section: "Bug Fixes"
      presetConfig: true
  prepare:
    - path: "@semantic-release/changelog"
      changelogFile: "docs/CHANGELOG.md"
      changelogTitle: "# Changelog"
    - path: "@semantic-release/git"
      assets:
        - "package.json"
        - "docs/CHANGELOG.md"
  publish:
    - path: "@semantic-release/github"
    - path: "@semantic-release/exec"
      publishCmd: "npm run build"
    - path: "@rimac-technology/semantic-release-s3"
      s3Bucket: "matthew-deploy-ci-test-dev-south-kr"
      directoryPath: "dist"
  success:
    - "@semantic-release/github"
  fail:
    - "@semantic-release/github"
