name: release
on:
  push:
    branches:
      - main
      - stage
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run test
  static-analize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run lint
      - run: tsc --build --dry
  release:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
    needs: [run-test, static-analize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npx semantic-release
